//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web11.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web11.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Enum_Gender_Female {
            get {
                return ResourceManager.GetString("Enum_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Enum_Gender_Male {
            get {
                return ResourceManager.GetString("Enum_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Enum_Gender_Other {
            get {
                return ResourceManager.GetString("Enum_Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Excel_col_1 {
            get {
                return ResourceManager.GetString("Excel_col_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hiệu cán bộ.
        /// </summary>
        public static string Excel_col_2 {
            get {
                return ResourceManager.GetString("Excel_col_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Excel_col_3 {
            get {
                return ResourceManager.GetString("Excel_col_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Excel_col_4 {
            get {
                return ResourceManager.GetString("Excel_col_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ chuyên môn.
        /// </summary>
        public static string Excel_col_5 {
            get {
                return ResourceManager.GetString("Excel_col_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thiết bị môn.
        /// </summary>
        public static string Excel_col_6 {
            get {
                return ResourceManager.GetString("Excel_col_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý kho - phòng.
        /// </summary>
        public static string Excel_col_7 {
            get {
                return ResourceManager.GetString("Excel_col_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo QLTB.
        /// </summary>
        public static string Excel_col_8 {
            get {
                return ResourceManager.GetString("Excel_col_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang làm việc.
        /// </summary>
        public static string Excel_col_9 {
            get {
                return ResourceManager.GetString("Excel_col_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DẠNH SÁCH CÁN BỘ - GIÁO VIÊN.
        /// </summary>
        public static string Excel_Title_Teacher {
            get {
                return ResourceManager.GetString("Excel_Title_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi, vui lòng liên hệ MISA để được trợ giúp !.
        /// </summary>
        public static string ExceptionMISA {
            get {
                return ResourceManager.GetString("ExceptionMISA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bạn nhập lớn hơn ngày hiện tại !.
        /// </summary>
        public static string ValidateDateMess {
            get {
                return ResourceManager.GetString("ValidateDateMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này phải là Email !.
        /// </summary>
        public static string ValidateEmailMess {
            get {
                return ResourceManager.GetString("ValidateEmailMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp hệ, vui lòng kiểm tra lại !.
        /// </summary>
        public static string ValidateErrMsg {
            get {
                return ResourceManager.GetString("ValidateErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này không được phép để trống !.
        /// </summary>
        public static string ValidateNotEmptyMess {
            get {
                return ResourceManager.GetString("ValidateNotEmptyMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại không hợp lệ !.
        /// </summary>
        public static string ValidatePhoneNMess {
            get {
                return ResourceManager.GetString("ValidatePhoneNMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã giáo viên không được phép trùng !.
        /// </summary>
        public static string ValidateTeacherCodeMess {
            get {
                return ResourceManager.GetString("ValidateTeacherCodeMess", resourceCulture);
            }
        }
    }
}
